version: "3.9"
services:
  build:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./build.sh
    working_dir: /work
    volumes:
      - .:/work
  pkg-debian:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./build-release.sh
    working_dir: /work/build
    volumes:
      - .:/work/build
      - ./output:/work
