; This the default configuration is bundled with bmath.
; Please copy this file to the following to make changes:
;   $HOME/.config/bmath/config.conf 
; See bmath-config(5) for options
; See https://en.wikipedia.org/wiki/INI_file for file format information

[format]
encodings = uint
human = false
justify = false
uppercase = false
