// Code generated by "stringer -type=SymbolType"; DO NOT EDIT.

package bmath

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SymbolTypeNone-0]
	_ = x[SymbolTypeFunction-1]
	_ = x[SymbolTypeVariable-2]
}

const _SymbolType_name = "SymbolTypeNoneSymbolTypeFunctionSymbolTypeVariable"

var _SymbolType_index = [...]uint8{0, 14, 32, 50}

func (i SymbolType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_SymbolType_index)-1 {
		return "SymbolType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SymbolType_name[_SymbolType_index[idx]:_SymbolType_index[idx+1]]
}
