// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package bmath

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenTypeNull-0]
	_ = x[TokenTypeNumber-1]
	_ = x[TokenTypeOperation-2]
	_ = x[TokenTypeShiftOperation-3]
	_ = x[TokenTypeLeftParenthesis-4]
	_ = x[TokenTypeRightParanthesis-5]
	_ = x[TokenTypeBitwiseNot-6]
	_ = x[TokenTypeAdditiveOp-7]
	_ = x[TokenTypeFactorOperation-8]
	_ = x[TokenTypeComma-9]
	_ = x[TokenTypeAssignment-10]
	_ = x[TokenTypeIdentifier-11]
	_ = x[TokenTypeTerminator-12]
	_ = x[TokenTypeVariable-13]
	_ = x[TokenTypeComment-14]
}

const _TokenType_name = "TokenTypeNullTokenTypeNumberTokenTypeOperationTokenTypeShiftOperationTokenTypeLeftParenthesisTokenTypeRightParanthesisTokenTypeBitwiseNotTokenTypeAdditiveOpTokenTypeFactorOperationTokenTypeCommaTokenTypeAssignmentTokenTypeIdentifierTokenTypeTerminatorTokenTypeVariableTokenTypeComment"

var _TokenType_index = [...]uint16{0, 13, 28, 46, 69, 93, 118, 137, 156, 180, 194, 213, 232, 251, 268, 284}

func (i TokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenType_index)-1 {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[idx]:_TokenType_index[idx+1]]
}
